### ISSUE TITLE
Needs a license file

### ISSUE THREAD

**Issue by taylorhughes** [lukesampson/figlet#1]
Would like to use this, but the project currently has no `LICENSE` file. (Given a contribution-friendly license I'd like to send a pull request or two to make this accessible as a library if you're up for it as well.)

Looks like original project has a BSD-style license: https://github.com/cmatsuoka/figlet/blob/master/LICENSE

**Comment by taylorhughes** [comment]
(Also kudos on this library being far more complete than others I've found in go :+1:)

**Comment by lukesampson** [comment]
Thanks for pointing that out. Yes, please send pull requests :smile:
